// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RouteServer.proto
// Protobuf C++ Version: 6.33.4

#ifndef RouteServer_2eproto_2epb_2eh
#define RouteServer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_RouteServer_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_RouteServer_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_RouteServer_2eproto;
}  // extern "C"
namespace message {
class RoutePackage;
struct RoutePackageDefaultTypeInternal;
extern RoutePackageDefaultTypeInternal _RoutePackage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RoutePackage_class_data_;
}  // namespace message
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace message {

// ===================================================================


// -------------------------------------------------------------------

class RoutePackage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:message.RoutePackage) */ {
 public:
  inline RoutePackage() : RoutePackage(nullptr) {}
  ~RoutePackage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RoutePackage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RoutePackage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RoutePackage(::google::protobuf::internal::ConstantInitialized);

  inline RoutePackage(const RoutePackage& from) : RoutePackage(nullptr, from) {}
  inline RoutePackage(RoutePackage&& from) noexcept
      : RoutePackage(nullptr, ::std::move(from)) {}
  inline RoutePackage& operator=(const RoutePackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoutePackage& operator=(RoutePackage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoutePackage& default_instance() {
    return *reinterpret_cast<const RoutePackage*>(
        &_RoutePackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RoutePackage& a, RoutePackage& b) { a.Swap(&b); }
  inline void Swap(RoutePackage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoutePackage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoutePackage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RoutePackage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RoutePackage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RoutePackage& from) { RoutePackage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RoutePackage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "message.RoutePackage"; }

  explicit RoutePackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RoutePackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoutePackage& from);
  RoutePackage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RoutePackage&& from) noexcept
      : RoutePackage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetUidFieldNumber = 2,
    kJsonDataFieldNumber = 3,
    kServerIdFieldNumber = 5,
    kMsgIdFieldNumber = 1,
    kErrorFieldNumber = 4,
  };
  // string targetUid = 2;
  void clear_targetuid() ;
  const ::std::string& targetuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_targetuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_targetuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_targetuid();
  void set_allocated_targetuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_targetuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_targetuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_targetuid();

  public:
  // string jsonData = 3;
  void clear_jsondata() ;
  const ::std::string& jsondata() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_jsondata(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_jsondata();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_jsondata();
  void set_allocated_jsondata(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_jsondata() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_jsondata(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_jsondata();

  public:
  // string serverId = 5;
  void clear_serverid() ;
  const ::std::string& serverid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_serverid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_serverid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_serverid();
  void set_allocated_serverid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_serverid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_serverid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_serverid();

  public:
  // int32 msgId = 1;
  void clear_msgid() ;
  ::int32_t msgid() const;
  void set_msgid(::int32_t value);

  private:
  ::int32_t _internal_msgid() const;
  void _internal_set_msgid(::int32_t value);

  public:
  // int32 error = 4;
  void clear_error() ;
  ::int32_t error() const;
  void set_error(::int32_t value);

  private:
  ::int32_t _internal_error() const;
  void _internal_set_error(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:message.RoutePackage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RoutePackage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr targetuid_;
    ::google::protobuf::internal::ArenaStringPtr jsondata_;
    ::google::protobuf::internal::ArenaStringPtr serverid_;
    ::int32_t msgid_;
    ::int32_t error_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RouteServer_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RoutePackage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RoutePackage

// int32 msgId = 1;
inline void RoutePackage::clear_msgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t RoutePackage::msgid() const {
  // @@protoc_insertion_point(field_get:message.RoutePackage.msgId)
  return _internal_msgid();
}
inline void RoutePackage::set_msgid(::int32_t value) {
  _internal_set_msgid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:message.RoutePackage.msgId)
}
inline ::int32_t RoutePackage::_internal_msgid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgid_;
}
inline void RoutePackage::_internal_set_msgid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgid_ = value;
}

// string targetUid = 2;
inline void RoutePackage::clear_targetuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RoutePackage::targetuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.RoutePackage.targetUid)
  return _internal_targetuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RoutePackage::set_targetuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.targetuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.RoutePackage.targetUid)
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::mutable_targetuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_targetuid();
  // @@protoc_insertion_point(field_mutable:message.RoutePackage.targetUid)
  return _s;
}
inline const ::std::string& RoutePackage::_internal_targetuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.targetuid_.Get();
}
inline void RoutePackage::_internal_set_targetuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::_internal_mutable_targetuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.targetuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RoutePackage::release_targetuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.RoutePackage.targetUid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.targetuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.targetuid_.Set("", GetArena());
  }
  return released;
}
inline void RoutePackage::set_allocated_targetuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.targetuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.targetuid_.IsDefault()) {
    _impl_.targetuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.RoutePackage.targetUid)
}

// string jsonData = 3;
inline void RoutePackage::clear_jsondata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.jsondata_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RoutePackage::jsondata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.RoutePackage.jsonData)
  return _internal_jsondata();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RoutePackage::set_jsondata(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.jsondata_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.RoutePackage.jsonData)
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::mutable_jsondata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_jsondata();
  // @@protoc_insertion_point(field_mutable:message.RoutePackage.jsonData)
  return _s;
}
inline const ::std::string& RoutePackage::_internal_jsondata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.jsondata_.Get();
}
inline void RoutePackage::_internal_set_jsondata(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.jsondata_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::_internal_mutable_jsondata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.jsondata_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RoutePackage::release_jsondata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.RoutePackage.jsonData)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.jsondata_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.jsondata_.Set("", GetArena());
  }
  return released;
}
inline void RoutePackage::set_allocated_jsondata(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.jsondata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.jsondata_.IsDefault()) {
    _impl_.jsondata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.RoutePackage.jsonData)
}

// int32 error = 4;
inline void RoutePackage::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t RoutePackage::error() const {
  // @@protoc_insertion_point(field_get:message.RoutePackage.error)
  return _internal_error();
}
inline void RoutePackage::set_error(::int32_t value) {
  _internal_set_error(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:message.RoutePackage.error)
}
inline ::int32_t RoutePackage::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_;
}
inline void RoutePackage::_internal_set_error(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// string serverId = 5;
inline void RoutePackage::clear_serverid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serverid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& RoutePackage::serverid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.RoutePackage.serverId)
  return _internal_serverid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RoutePackage::set_serverid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.serverid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.RoutePackage.serverId)
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::mutable_serverid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_serverid();
  // @@protoc_insertion_point(field_mutable:message.RoutePackage.serverId)
  return _s;
}
inline const ::std::string& RoutePackage::_internal_serverid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.serverid_.Get();
}
inline void RoutePackage::_internal_set_serverid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serverid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RoutePackage::_internal_mutable_serverid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.serverid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RoutePackage::release_serverid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.RoutePackage.serverId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.serverid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.serverid_.Set("", GetArena());
  }
  return released;
}
inline void RoutePackage::set_allocated_serverid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.serverid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.serverid_.IsDefault()) {
    _impl_.serverid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.RoutePackage.serverId)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace message


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // RouteServer_2eproto_2epb_2eh
