// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RouteServer.proto
// Protobuf C++ Version: 6.33.4

#include "../headers/RouteServer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace message {

inline constexpr RoutePackage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        targetuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        jsondata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        serverid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgid_{0},
        error_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RoutePackage::RoutePackage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RoutePackage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RoutePackageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutePackageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutePackageDefaultTypeInternal() {}
  union {
    RoutePackage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutePackageDefaultTypeInternal _RoutePackage_default_instance_;
}  // namespace message
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_RouteServer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_RouteServer_2eproto = nullptr;
const ::uint32_t
    TableStruct_RouteServer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_.msgid_),
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_.targetuid_),
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_.jsondata_),
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::message::RoutePackage, _impl_.serverid_),
        3,
        0,
        1,
        4,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::message::RoutePackage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::message::_RoutePackage_default_instance_._instance,
};
const char descriptor_table_protodef_RouteServer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021RouteServer.proto\022\007message\"c\n\014RoutePac"
    "kage\022\r\n\005msgId\030\001 \001(\005\022\021\n\ttargetUid\030\002 \001(\t\022\020"
    "\n\010jsonData\030\003 \001(\t\022\r\n\005error\030\004 \001(\005\022\020\n\010serve"
    "rId\030\005 \001(\t2V\n\014RouteService\022F\n\022RouteMessag"
    "eStream\022\025.message.RoutePackage\032\025.message"
    ".RoutePackage(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_RouteServer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_RouteServer_2eproto = {
    false,
    false,
    225,
    descriptor_table_protodef_RouteServer_2eproto,
    "RouteServer.proto",
    &descriptor_table_RouteServer_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_RouteServer_2eproto::offsets,
    file_level_enum_descriptors_RouteServer_2eproto,
    file_level_service_descriptors_RouteServer_2eproto,
};
namespace message {
// ===================================================================

class RoutePackage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RoutePackage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_._has_bits_);
};

RoutePackage::RoutePackage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutePackage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.RoutePackage)
}
PROTOBUF_NDEBUG_INLINE RoutePackage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::message::RoutePackage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        targetuid_(arena, from.targetuid_),
        jsondata_(arena, from.jsondata_),
        serverid_(arena, from.serverid_) {}

RoutePackage::RoutePackage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RoutePackage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutePackage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RoutePackage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, msgid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, msgid_),
           offsetof(Impl_, error_) -
               offsetof(Impl_, msgid_) +
               sizeof(Impl_::error_));

  // @@protoc_insertion_point(copy_constructor:message.RoutePackage)
}
PROTOBUF_NDEBUG_INLINE RoutePackage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        targetuid_(arena),
        jsondata_(arena),
        serverid_(arena) {}

inline void RoutePackage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, msgid_),
           0,
           offsetof(Impl_, error_) -
               offsetof(Impl_, msgid_) +
               sizeof(Impl_::error_));
}
RoutePackage::~RoutePackage() {
  // @@protoc_insertion_point(destructor:message.RoutePackage)
  SharedDtor(*this);
}
inline void RoutePackage::SharedDtor(MessageLite& self) {
  RoutePackage& this_ = static_cast<RoutePackage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.targetuid_.Destroy();
  this_._impl_.jsondata_.Destroy();
  this_._impl_.serverid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RoutePackage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RoutePackage(arena);
}
constexpr auto RoutePackage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RoutePackage),
                                            alignof(RoutePackage));
}
constexpr auto RoutePackage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RoutePackage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RoutePackage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RoutePackage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RoutePackage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RoutePackage>(), &RoutePackage::ByteSizeLong,
              &RoutePackage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_._cached_size_),
          false,
      },
      &RoutePackage::kDescriptorMethods,
      &descriptor_table_RouteServer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RoutePackage_class_data_ =
        RoutePackage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RoutePackage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RoutePackage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RoutePackage_class_data_.tc_table);
  return RoutePackage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 54, 2>
RoutePackage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RoutePackage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::message::RoutePackage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 msgId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RoutePackage, _impl_.msgid_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.msgid_)}},
    // string targetUid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.targetuid_)}},
    // string jsonData = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.jsondata_)}},
    // int32 error = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RoutePackage, _impl_.error_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.error_)}},
    // string serverId = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 2, 0,
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.serverid_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 msgId = 1;
    {PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.msgid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string targetUid = 2;
    {PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.targetuid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string jsonData = 3;
    {PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.jsondata_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 error = 4;
    {PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.error_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string serverId = 5;
    {PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.serverid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\0\11\10\0\10\0\0"
    "message.RoutePackage"
    "targetUid"
    "jsonData"
    "serverId"
  }},
};
PROTOBUF_NOINLINE void RoutePackage::Clear() {
// @@protoc_insertion_point(message_clear_start:message.RoutePackage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.targetuid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.jsondata_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.serverid_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.msgid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.error_) -
        reinterpret_cast<char*>(&_impl_.msgid_)) + sizeof(_impl_.error_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RoutePackage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RoutePackage& this_ = static_cast<const RoutePackage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RoutePackage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RoutePackage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:message.RoutePackage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 msgId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_msgid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_msgid(), target);
    }
  }

  // string targetUid = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_targetuid().empty()) {
      const ::std::string& _s = this_._internal_targetuid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.RoutePackage.targetUid");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string jsonData = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_jsondata().empty()) {
      const ::std::string& _s = this_._internal_jsondata();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.RoutePackage.jsonData");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // int32 error = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_error() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_error(), target);
    }
  }

  // string serverId = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_serverid().empty()) {
      const ::std::string& _s = this_._internal_serverid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.RoutePackage.serverId");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.RoutePackage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RoutePackage::ByteSizeLong(const MessageLite& base) {
  const RoutePackage& this_ = static_cast<const RoutePackage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RoutePackage::ByteSizeLong() const {
  const RoutePackage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:message.RoutePackage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string targetUid = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_targetuid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_targetuid());
      }
    }
    // string jsonData = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_jsondata().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_jsondata());
      }
    }
    // string serverId = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_serverid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_serverid());
      }
    }
    // int32 msgId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_msgid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_msgid());
      }
    }
    // int32 error = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_error() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_error());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RoutePackage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RoutePackage*>(&to_msg);
  auto& from = static_cast<const RoutePackage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:message.RoutePackage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_targetuid().empty()) {
        _this->_internal_set_targetuid(from._internal_targetuid());
      } else {
        if (_this->_impl_.targetuid_.IsDefault()) {
          _this->_internal_set_targetuid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_jsondata().empty()) {
        _this->_internal_set_jsondata(from._internal_jsondata());
      } else {
        if (_this->_impl_.jsondata_.IsDefault()) {
          _this->_internal_set_jsondata("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_serverid().empty()) {
        _this->_internal_set_serverid(from._internal_serverid());
      } else {
        if (_this->_impl_.serverid_.IsDefault()) {
          _this->_internal_set_serverid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_msgid() != 0) {
        _this->_impl_.msgid_ = from._impl_.msgid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_error() != 0) {
        _this->_impl_.error_ = from._impl_.error_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RoutePackage::CopyFrom(const RoutePackage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:message.RoutePackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RoutePackage::InternalSwap(RoutePackage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.targetuid_, &other->_impl_.targetuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.jsondata_, &other->_impl_.jsondata_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serverid_, &other->_impl_.serverid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.error_)
      + sizeof(RoutePackage::_impl_.error_)
      - PROTOBUF_FIELD_OFFSET(RoutePackage, _impl_.msgid_)>(
          reinterpret_cast<char*>(&_impl_.msgid_),
          reinterpret_cast<char*>(&other->_impl_.msgid_));
}

::google::protobuf::Metadata RoutePackage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace message
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_RouteServer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
