// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RouteServer.proto

#include "../headers/RouteServer.pb.h"
#include "../headers/RouteServer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace message {

static const char* RouteService_method_names[] = {
  "/message.RouteService/RouteMessageStream",
};

std::unique_ptr< RouteService::Stub> RouteService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RouteService::Stub> stub(new RouteService::Stub(channel, options));
  return stub;
}

RouteService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RouteMessageStream_(RouteService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::message::RoutePackage, ::message::RoutePackage>* RouteService::Stub::RouteMessageStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::message::RoutePackage, ::message::RoutePackage>::Create(channel_.get(), rpcmethod_RouteMessageStream_, context);
}

void RouteService::Stub::async::RouteMessageStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::message::RoutePackage,::message::RoutePackage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::message::RoutePackage,::message::RoutePackage>::Create(stub_->channel_.get(), stub_->rpcmethod_RouteMessageStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::message::RoutePackage, ::message::RoutePackage>* RouteService::Stub::AsyncRouteMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::message::RoutePackage, ::message::RoutePackage>::Create(channel_.get(), cq, rpcmethod_RouteMessageStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::message::RoutePackage, ::message::RoutePackage>* RouteService::Stub::PrepareAsyncRouteMessageStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::message::RoutePackage, ::message::RoutePackage>::Create(channel_.get(), cq, rpcmethod_RouteMessageStream_, context, false, nullptr);
}

RouteService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RouteService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RouteService::Service, ::message::RoutePackage, ::message::RoutePackage>(
          [](RouteService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::message::RoutePackage,
             ::message::RoutePackage>* stream) {
               return service->RouteMessageStream(ctx, stream);
             }, this)));
}

RouteService::Service::~Service() {
}

::grpc::Status RouteService::Service::RouteMessageStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::message::RoutePackage, ::message::RoutePackage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message
#include <grpcpp/ports_undef.inc>

